import Header from '@/Components/header'
import Footer from '@/Components/footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css" />
      </head>
      <body>
      <Header  />
        <div className='container p-3'>
        {children}
        </div>
        <Footer />
        
      </body>
    </html>
  )
}
